version=${project.version}
buildtime=${timestamp}
builder=${env.USERNAME}
builderName=${backup.build.user.name}
builderEmail=${backup.build.user.email}
buildhost=${env.COMPUTERNAME}
buildOs=${os.name}
gitBranch=${backup.branch}
gitCommitIdDescribe=${backup.commit.id.describe}
gitCommitId=${backup.commit.id.full}
gitCommitUrl=${backup.remote.origin.url}
gitCommitTime=${backup.commit.time}
gitDirty=${backup.dirty}